version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: deploy-1
    IMAGE_TAG: latest
    AWS_ACCOUNT_ID: 566312720731
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws codeartifact login --tool npm --repository npm --domain deploy-1 --domain-owner 566312720731 --region eu-central-1
  build:
    commands:
      - npm ci
      - npm run build
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker push $IMAGE
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $IMAGE > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
